### ISSUE TITLE
Why are you asking for discord email and password??

### ISSUE THREAD

**Issue by qwertyquerty** [ethanrasmussen/CalendarConnect#1]
You don't even use it anywhere, and there is no reason you would need it.

Furthermore you should never ask for that information yourself, and instead just use discord's oauth2 service.

**Comment by ethanrasmussen** [comment]
This was part of the deprecated version of the program, however it was never fully updated (and thus never fully removed). The deprecated version bypassed oauth2 verification via unofficial API access, allowing profile updates not possible in user accounts via the official API. 

If this program is ever properly updated, it would be rewritten with oauth2.
